name: Install
description: Install everything for the repo

inputs:
  node-version:
    description: Version of Node to use
    default: 22.x

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: 🏗 Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: 🗃️ Get pnpm Store Directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: 🏗 Setup Cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-${{ inputs.node-version }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.node-version }}-pnpm-store-
          ${{ runner.os }}-pnpm-store-

    - name: 📦 Install Deps
      run: pnpm install
      shell: bash
